name: Create release

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  migration-test:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get version from tag
        run: |
          TAG=${{ github.ref_name }}
          echo "VERSION=${TAG#v}" >> $GITHUB_ENV

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
            channel: stable
            flutter-version: 3.32.7
            cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Generate drift database file
        run: dart run build_runner build

      - name: Write configs for release
        run: |
          echo $KEY_STORE | base64 --decode > $GITHUB_WORKSPACE/upload-keystore.jks
          echo "storePassword=$STORE_SECRET" > $GITHUB_WORKSPACE/android/key.properties
          echo "keyPassword=$STORE_SECRET" >> $GITHUB_WORKSPACE/android/key.properties
          echo "keyAlias=upload" >> $GITHUB_WORKSPACE/android/key.properties
          echo "storeFile=$GITHUB_WORKSPACE/upload-keystore.jks" >> $GITHUB_WORKSPACE/android/key.properties

      - name: Build Android APK
        run: flutter build apk --build-name=${{ env.VERSION }}
      
      - uses: ncipollo/release-action@v1
        with:
          artifacts: ./build/app/outputs/flutter-apk/app-release.apk*
          generateReleaseNotes: true

      